image: Visual Studio 2017
environment:
  DOCKER_TARGET: simaos/nanopsbuild
  DOCKER_USER:
    secure: 09M6/EHaWHd+zNyhVD2LNQ==
  DOCKER_PASS:
    secure: gvgvfMOklGvBlsbXpw68WQ==
install:
  - docker version
  - echo DOCKER_TARGET is %DOCKER_TARGET%
build_script:
  - docker build -t %DOCKER_TARGET% -f Dockerfile .
test_script:
  - docker run %DOCKER_TARGET%
deploy_script:
  - docker login -u="%DOCKER_USER%" -p="%DOCKER_PASS%"
  - docker push $env:DOCKER_TARGET
