image: Visual Studio 2017
environment:
  DOCKER_TARGET: simaos/nanopsbuild
  DOCKER_USER:
    secure: 09M6/EHaWHd+zNyhVD2LNQ==
  DOCKER_PASS:
    secure: gvgvfMOklGvBlsbXpw68WQ==
install:
  - docker version
  - echo DOCKER_TARGET is %DOCKER_TARGET%
  - systeminfo
build_script:
  - ps: .\Invoke-Build.ps1 -DockerTarget $env:DOCKER_TARGET
test_script:
  - ps: .\Invoke-Test.ps1 -DockerTarget $env:DOCKER_TARGET
deploy_script:
  - docker login -u="%DOCKER_USER%" -p="%DOCKER_PASS%"
  - ps: .\Invoke-Deploy.ps1 -DockerTarget=$env:DOCKER_TARGET
